#
# Copyright (C) 2025 The LineageOS Project
#
# SPDX-License-Identifier: Apache-2.0
#

# This file is generated by setup-makefiles.sh

# We don't need to build any of the vendor blobs from source
TARGET_SKIP_VENDOR_BUILD := true
