#
# Copyright (C) 2025 The LineageOS Project
#
# SPDX-License-Identifier: Apache-2.0
#

# This file is generated by setup-makefiles.sh

# Inherit from the proprietary version of BoardConfigVendor.mk
-include vendor/oneplus/udon/BoardConfigVendor.mk
